name: reverse_nominatim
description: OSM Nominatim reverse geocoder.
version: 0.0.1
author: Ilya Yachin

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  json_annotation: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.7
  json_serializable: ^3.5.1

flutter:
